# Generated by Django 5.0.2 on 2024-02-17 23:59

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(app.models.GenderEnum['MALE'], 'MALE'), (app.models.GenderEnum['FEMALE'], 'FEMALE')])),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('postcode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(app.models.GenderEnum['MALE'], 'MALE'), (app.models.GenderEnum['FEMALE'], 'FEMALE')], max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('definition', models.TextField()),
                ('salary', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[(app.models.JobTypeEnum['Hybrid'], 'Hybrid'), (app.models.JobTypeEnum['Remote'], 'Remote'), (app.models.JobTypeEnum['OnSite'], 'On-Site')])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recruiter')),
            ],
        ),
    ]
