# Generated by Django 5.0.2 on 2024-02-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(),
        ),
    ]
